Repository brunopulis/awesome-a11y, pull requests merged in 2022-04, with the labels that each got.

#158 fix: remove broken link
  topics/courses.md
  topics/meetups.md
Labels: bug

#159 feat: add badges
  README.md
Labels: enhancement

#160 Added Reasonable Colors to Other Resources
  topics/other-resources.md
Labels: feature proposal
